[package]
name = "rubyfmt-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
rubyfmt = { git = "https://github.com/fables-tales/rubyfmt", rev = "f7658081e074a17fda5d9270ef4636d1a27848c1", default-features = false }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
strip = true
