[package]
name = "rubyfmt-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
rubyfmt = { git = "https://github.com/fables-tales/rubyfmt", rev = "f31f576fa1d50bb548c7180bdb6dc30a3fe19be3", default-features = false }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
strip = true
